# Generated by Django 3.1.7 on 2021-04-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
